---
- name: Install Tomcat
  hosts: G1
  become: true
  vars:
    tomcat_admin_username: admin
    tomcat_admin_password: admin123
  
  tasks:
    
  - name: Ensure System Packages Updated
    yum:
      update_cache: yes
    when: ansible_os_family == 'RedHat'

  - name: Ensure System Packages Updated
    apt:
      update_cache: yes
    when: ansible_os_family == 'Debian'

  - name: Install Java
    yum:
      name: java-11-openjdk-devel
      state: present
    when: ansible_os_family == 'RedHat'

  - name: Install Java
    apt:
      name: openjdk-11-jdk
      state: present
    when: ansible_os_family == 'Debian'

  - name: Create a Directory to extract tomcat into
    file:
      path: /opt/tomcat
      state: directory

  - name: Download Tomcat
    get_url:
      url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz"
      dest: /opt/
      
  - name: Extract Tomcat
    unarchive:
      src: /opt/apache-tomcat-9.0.54.tar.gz
      dest: /opt/
      remote_src: yes

   name: Move files to the /opt/tomcat directory
    become: yes
    shell: "mv -un /opt/apache-tomcat-9.0.54/* /opt/tomcat/"

  - name: Set permissions for the WAR file
    file:
      path: /opt/tomcat
      mode: "0755"
      recurse: yes

  - name: Configure Tomcat Users
    template:
      src: tomcat-users.xml.j2
      dest: /opt/tomcat/conf/tomcat-users.xml
  
  - name: Start Tomcat Service
    shell: nohup /opt/tomcat/bin/startup.sh &
    when: ansible_os_family == 'RedHat'

  - name: Start Tomcat Service
    shell: nohup /opt/tomcat/bin/startup.sh &
    when: ansible_os_family == 'Debian'

... 