---
- name: Deploy WAR file to Tomcat Servers
  hosts: G1
  become: yes
  
  tasks:
    - name: Ensure the destination directory exists
      file:
        path: "~/JavaWebApp/target/WebAppCal-0.0.6.war"
        state: directory
        mode: '0755'
    
    - name: Copy WAR file
      become: true
      copy:
        src: ~/JavaWebApp/target/WebAppCal-0.0.6.war
        dest: /opt/apache-tomcat-9.0.54/webapps/
        remote_src: yes

    - name: Set permissions for the WAR file
      file:
        path: /opt/apache-tomcat-9.0.54/webapps/*.war"
        owner: admin
        group: G1
        mode: "0644"  
    #- name: Restart Tomcat
     # service:
      #  name: apache-tomcat
       # state: restarted

    - name: Start Tomcat Service
      shell: nohup /opt/apache-tomcat-9.0.54/bin/startup.sh &
   
          
... 