---
- name: Deploy WAR file to Tomcat Servers
  hosts: G1
  become: yes
  
  tasks:

    - name: Change ownership recursively
      become: yes  # This ensures the task runs with elevated privileges (sudo)
      file:
        path: /opt/apache-tomcat-9.0.54/
        owner: ubuntu
        group: ubuntu
        recurse: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Change ownership recursively
      become: yes  # This ensures the task runs with elevated privileges (sudo)
      file:
        path: /opt/apache-tomcat-9.0.54/
        owner: centos
        group: centos
        recurse: yes
      when: ansible_distribution == 'CentOS'

    - name: Copy WAR file
      become: true
      copy:
        src: /home/centos/JavaWebApp/target/WebAppCal-0.0.6.war
        dest: /opt/apache-tomcat-9.0.54/webapps/
        remote_src: yes

    #- name: Restart Tomcat
     # service:
      #  name: apache-tomcat
       # state: restarted

    - name: Start Tomcat Service
      shell: nohup /opt/apache-tomcat-9.0.54/bin/startup.sh &
   
          
... 