---
- name: Deploy WAR file to Tomcat Servers
  hosts: G1
  become: yes
  
  tasks:
    
    - name: Copy the WAR file
      ansible.builtin.copy:
        src: "/home/centos/JavaWebApp/target/WebAppCal-0.0.6.war"
        dest: /opt/tomcat/webapps/
        remote_src: yes
    

    - name: Start Tomcat Service
      shell: nohup /opt/tomcat/bin/startup.sh &
   
          
... 