---
- name: Deploy WAR file to Tomcat Servers
  hosts: G1
  become: yes
  
  tasks:

    - name: Copy WAR file
      become: true
      copy:
        src: /home/centos/JavaWebApp/target/WebAppCal-0.0.6.war
        dest: /opt/tomcat/webapps/
        remote_src: yes

    #- name: Restart Tomcat
     # service:
      #  name: apache-tomcat
       # state: restarted

    - name: Start Tomcat Service
      shell: nohup /opt/bin/startup.sh &
   
          
... 